services:
  - type: web
    name: customer-feedback-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: Swa5athi*
      - key: DB_NAME
        value: cfms
      - key: DB_PORT
        value: 3306
      - key: FRONTEND_URL
        value: https://customer-feedback-management-system-vyoy.onrender.com 